# Generated by Django 3.1 on 2021-01-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210120_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='static/images/dog.jpg', upload_to='profile/'),
        ),
    ]
