# Generated by Django 3.1 on 2021-01-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Booked', 'Booked')], max_length=60, null=True),
        ),
    ]
