# Generated by Django 3.1 on 2021-01-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionManagement', '0003_auto_20210103_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dog_image',
            field=models.FileField(null=True, upload_to='assets/'),
        ),
    ]
