# Generated by Django 3.1 on 2021-01-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionManagement', '0004_dog_dog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='dog_image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
