# Generated by Django 3.1 on 2021-01-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionManagement', '0005_auto_20210107_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
