# Generated by Django 3.1 on 2021-01-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionManagement', '0007_auto_20210111_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
