# Generated by Django 3.1 on 2021-01-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionManagement', '0008_auto_20210112_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='status',
            new_name='is_requested',
        ),
    ]
