# Generated by Django 3.1 on 2021-01-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionManagement', '0009_auto_20210113_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionqueue',
            name='dog',
        ),
        migrations.RemoveField(
            model_name='adoptionqueue',
            name='status',
        ),
        migrations.AddField(
            model_name='adoptionqueue',
            name='age',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='adoptionqueue',
            name='dog_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='adoptionqueue',
            name='further_info',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='adoptionqueue',
            name='reason',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='is_requested',
            field=models.BooleanField(),
        ),
    ]
