# Generated by Django 3.1 on 2021-01-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionManagement', '0010_auto_20210114_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionqueue',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='adoptionqueue',
            name='further_info',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Further information (optional)'),
        ),
        migrations.AlterField(
            model_name='adoptionqueue',
            name='reason',
            field=models.CharField(max_length=150, null=True, verbose_name='Reason for registering'),
        ),
    ]
