# Generated by Django 3.1 on 2021-01-15 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionManagement', '0012_auto_20210115_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='dog',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='adoptionManagement.dog'),
        ),
    ]
