# Generated by Django 3.1 on 2021-01-15 12:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionManagement', '0014_auto_20210115_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requests',
            name='dog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adoptionManagement.dog'),
        ),
    ]
