# Generated by Django 3.1.7 on 2021-05-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptionManagement', '0017_adoptionqueue_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='status',
        ),
    ]
